import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import farmerPic from "../public/assets/farmer.jpeg"
import styles from '../styles/Home.module.css'
import { getData } from './api/randomText'

type Props = {
  data: String
}

const Home: NextPage<Props> = ({ data }) => {
  return (
    <div className={styles.container}>
      <div className={styles.main}>
        <Head>
          <title>NUS Container Course</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Image alt="poor ol farmer" src={farmerPic} width={200} height={200} />
        <h3>
          {data}
        </h3>
      </div>
      <p>
        Repository: https://github.com/tengfone-govtech/nus-container-course
      </p>
    </div>
  )
}

export default Home

export async function getServerSideProps() {
  const jsonData = await getData()
  return { props: { data: jsonData } };
}